//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signature_Hotel_Management_System.Content.WebForms._3.Dashboard
{


    public partial class Dashboard
    {
    }
}
